"""Public storage boundaries for legal domain services and adapters."""

from .repositories import (
    BatchWriteResult,
    DocumentRepository,
    EntityNotFoundError,
    EventRepository,
    ProvenanceRepository,
    ProvisionRepository,
    RepositoryConflictError,
    RepositoryError,
    RepositoryIntegrityError,
    SnapshotRepository,
    TemporalGraphRepository,
    TemporalUnitOfWork,
    TransactionError,
    VersionTransitionResult,
    VersionRepository,
    WriteDisposition,
    WriteResult,
)
from .retrieval import (
    EvidenceReranker,
    LexicalMatch,
    LexicalRecord,
    LexicalRepository,
    LexicalSearchQuery,
    QueryEncoder,
)
from .vector import (
    VectorMatch,
    VectorRepository,
    VectorSearchQuery,
    VersionEmbedding,
)

__all__ = [
    "BatchWriteResult",
    "DocumentRepository",
    "EntityNotFoundError",
    "EventRepository",
    "EvidenceReranker",
    "LexicalMatch",
    "LexicalRecord",
    "LexicalRepository",
    "LexicalSearchQuery",
    "ProvenanceRepository",
    "ProvisionRepository",
    "RepositoryConflictError",
    "RepositoryError",
    "RepositoryIntegrityError",
    "QueryEncoder",
    "SnapshotRepository",
    "TemporalGraphRepository",
    "TemporalUnitOfWork",
    "TransactionError",
    "VersionTransitionResult",
    "VectorMatch",
    "VectorRepository",
    "VectorSearchQuery",
    "VersionEmbedding",
    "VersionRepository",
    "WriteDisposition",
    "WriteResult",
]
